#----------------------------------------------------------------------------------------------------------------------#
# [1vs1] created by GaaehHacked
# Discord: ᴠ̷ᴇ̷ɴ̷ᴏ̷ᴍ̷#0187
# Version: 1.0
# This plugin is copy-right saved also do not sell, re-code or say thats yours!
#----------------------------------------------------------------------------------------------------------------------#